ExplorarTour/Models/Card.cs
namespace ExplorarTour.Models
{
    public class Card
    {
        public int CAID { get; set; }
        public string CANome { get; set; }
        public string CADescricaoP { get; set; }
        public string CADescricaoG { get; set; }
        public DateTime CAData { get; set; }
        public string? CAImagem { get; set; }
        public int favorito { get; set; }
    }
}

ExplorarTour/Models/ErrorViewModel.cs
namespace ExplorarTour.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExplorarTour/Models/Usuario.cs
using ExplorarTour.Enums;

namespace ExplorarTour.Models
{
    public class Usuario
    {
        public int ID { get; set; }
        public string Nome { get; set; }

        public string LOGIN_ { get; set; }   
        public string Email { get; set; }
        public string Senha { get; set; }
        public string Perfil { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime? DataAtualizacao { get; set; }
    }
}

ExplorarTour/Controllers/CadastroController.cs
using ExplorarTour.DAL;
using ExplorarTour.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExplorarTour.Controllers
{
    public class CadastroController : Controller
    {
        UsuarioDAO dados = new UsuarioDAO();

        [HttpGet]
        public IActionResult Cadastrar()
        {
            ViewBag.listaAluno = dados.getTodosAluno();
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string senha)
        {
            List<Usuario> a = new List<Usuario>();  
            a = dados.getTodosAluno();
            bool user = a.Any(x => x.Email == email && x.Senha == senha);   

            return View();
        }

        [HttpPost]
        public IActionResult Create(string nome, string senha, string email)
        {

            Usuario novoAluno = new Usuario();

            novoAluno.Nome = nome;
            novoAluno.Senha = senha;
            novoAluno.Email = email;    
            novoAluno.DataCadastro = DateTime.Now;
            novoAluno.Perfil = "oi";
            novoAluno.LOGIN_ = "sim";

            dados.insertAluno(novoAluno);
            return RedirectToAction("Cadastrar");
        }

        public IActionResult Login()
        {
            return View();
        }
    }
}

ExplorarTour/Controllers/DestinosController.cs
using ExplorarTour.DAL;
using ExplorarTour.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExplorarTour.Controllers
{
    public class DestinosController : Controller
    {
        CardDAO dados = new CardDAO();
        public IActionResult Index()
        {
            ViewBag.listaCard = dados.getTodosCards();
            ViewBag.listaCardCount = dados.getTodosCards().Count();
            return View();
        }

        [HttpGet]
        public IActionResult Criacao()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Descricao(int id)
        {
            ViewBag.cardAtualizar = dados.getTodosCards().Where(x => x.CAID == id).FirstOrDefault();
            return View();
        }

        [HttpPost]
        public IActionResult Create(string nome, string descricaop, string descricaog)
        {


            Card novoCard = new Card();

            novoCard.CANome = nome;
            novoCard.CADescricaoP = descricaop;
            novoCard.CADescricaoG = descricaog;
            novoCard.CAData = DateTime.Now;


            dados.insertCard(novoCard);
            return RedirectToAction("Index");
        }

  

        [HttpGet]
        public IActionResult Favoritar(int id)
        {

            Card favoritaCard = new Card();

            ViewBag.cardAtualizar = dados.getTodosCards().Where(x => x.CAID == id).FirstOrDefault();
            if (ViewBag.cardAtualizar.favorito == 1)
            {
                favoritaCard.favorito = 0;
            }
            else
            {
                favoritaCard.favorito = 1;
            }



        
            favoritaCard.CAID = id;


            dados.favoritarCard(favoritaCard);

            return RedirectToAction("Index");
        }

        public ActionResult Pesquisar(string termoPesquisa)
        {

     
                // Lógica de pesquisa aqui (por exemplo, consultar no banco de dados)
               var produtos = dados.getTodosCards()
                    .Where(p => p.CANome.Contains(termoPesquisa, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            
 

            // Retornar os resultados da pesquisa para a exibição
            return PartialView("_ResultadoPesquisa", produtos);
        }
    }
}

ExplorarTour/Controllers/FavoritosController.cs
using ExplorarTour.DAL;
using ExplorarTour.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExplorarTour.Controllers
{
    public class FavoritosController : Controller
    {
        CardDAO dados = new CardDAO();
        public IActionResult Index()
        {
            ViewBag.listaCardFavorito = dados.getTodosCards().Where(x => x.favorito == 1);
            ViewBag.listaCardFavoritoCount = dados.getTodosCards().Where(x => x.favorito == 1).Count();
            return View();
        }

        [HttpGet]
        public IActionResult Favoritar(int id)
        {

            Card favoritaCard = new Card();

            ViewBag.cardAtualizar = dados.getTodosCards().Where(x => x.CAID == id).FirstOrDefault();
            if (ViewBag.cardAtualizar.favorito == 1)
            {
                favoritaCard.favorito = 0;
            }
            else
            {
                favoritaCard.favorito = 1;
            }




            favoritaCard.CAID = id;


            dados.favoritarCard(favoritaCard);

            return RedirectToAction("Index");
        }

    }
}

ExplorarTour/Controllers/HomeController.cs
using ExplorarTour.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExplorarTour.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExplorarTour/Views/Destinos/Criacao.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
    <style>
        .content i {
            margin-bottom: 41px;
        }

        .container {
            border-radius: 8px;
            box-shadow: 5px 5px 5px gray;
            padding: 50px 40px 20px 40px;
            box-sizing: border-box;
            font-family: sans-serif;
            color: #737373;
            border: 1px solid rgb(219, 219, 219);
            text-align: center;
            background: white;
        }

            .container svg {
                width: 16px;
                height: auto;
            }

        .content__form {
            display: flex;
            flex-direction: column;
            row-gap: 14px;
        }

        .content__inputs {
            display: flex;
            flex-direction: column;
            row-gap: 8px;
        }

        .content__form label {
            border: 1px solid rgb(219, 219, 219);
            display: flex;
            align-items: center;
            position: relative;
            min-width: 268px;
            height: 38px;
            background: rgb(250, 250, 250);
            border-radius: 3px;
        }

        .content__form span {
            position: absolute;
            text-overflow: ellipsis;
            transform-origin: left;
            font-size: 12px;
            left: 8px;
            pointer-events: none;
            transition: transform ease-out .1s
        }

        .content__form input {
            width: 100%;
            background: inherit;
            border: 0;
            outline: none;
            padding: 9px 8px 7px 8px;
            text-overflow: ellipsis;
            font-size: 16px;
            vertical-align: middle;
        }

            .content__form input:valid + span {
                transform: scale(calc(10 / 12)) translateY(-10px);
            }

            .content__form input:valid {
                padding: 14px 0 2px 8px;
                font-size: 12px;
            }

        .content__or-text {
            display: flex;
            justify-content: space-between;
            align-items: center;
            text-transform: uppercase;
            font-size: 13px;
            column-gap: 18px;
            margin-top: 18px;
        }

            .content__or-text span:nth-child(3),
            .content__or-text span:nth-child(1) {
                display: block;
                width: 100%;
                height: 1px;
                background-color: rgb(219, 219, 219);
            }

        .content__forgot-buttons {
            display: flex;
            flex-direction: column;
            margin-top: 28px;
            row-gap: 14px;
        }

            .content__forgot-buttons button {
                display: flex;
                justify-content: center;
                align-items: center;
                column-gap: 8px;
                background: none;
                border: none;
                cursor: pointer;
                font-size: 12px;
                color: #00376b;
            }

                .content__forgot-buttons button:first-child {
                    color: #385185;
                    font-size: 14px;
                    font-weight: 600;
                }

        .content__form button {
            background: rgb(0, 149, 246);
            color: white;
            border: none;
            border-radius: 8px;
            font-weight: 700;
            font-size: 14px;
            padding: 7px 16px;
            cursor: pointer;
        }

            .content__form button:hover {
                background: rgb(24, 119, 242);
            }

            .content__form button:active:not(:hover) {
                background: rgb(0, 149, 246);
                opacity: .7;
            }

        body {
            align-items: center;
            justify-content: center;
        }

        }
    </style>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg " style="background-color:rgba(45,136,253,1); color:white;">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="color:white; font-weight:bold;">Explora Tour</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">

                    <a class="nav-link" asp-controller="Home" asp-action="Index" style="color:white; display:flex;">
                        <img style="width:22px;" src="~/img/casa (1).png" />
                        <span>&nbsp;Início</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Destinos" asp-action="Index" style="color:white;">
                        <img style="width:22px;" src="~/img/mapas-e-bandeiras.png" />
                        <span>&nbsp;Destinos</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Favoritos" asp-action="Index" style="color:white;">
                        <img style="width:22px;" src="~/img/favorito.png" />
                        <span>&nbsp;Favoritos</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cadastro" asp-action="Cadastrar" style="color:white;">
                        <img style="width:22px;" src="~/img/pessoa.png" />
                        <span>&nbsp;Login</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div data-aos="fade-up" style="width: 100%; display: flex;  justify-content: center; margin-top:30px;">
        <div style="width: 80%;">



            <form onsubmit="return sim();" method="post" action="Create" class="content__form" style="display: block">

                <div class="content__inputs">
                    <label for="nome">
                     
                        <input type="text" id="nome" name="nome" required>
                           <span>Nome do Destino</span>

                    </label>
                    <label for="descricaop">
                    
                        <input type="text" id="descricaop" name="descricaop" required>
                        <span>Descrição Resumida</span>

                    </label>
                    <label for="descricaog">
                   
                        <input type="text" id="descricaog" name="descricaog" required>
                        <span>Descrição Extensa</span>
                    </label>

                </div>

                <br>
                <button type="submit">CADASTRAR</button>
            </form>
        </div>
    </div>

    </body>
</html>

ExplorarTour/Views/Destinos/Descricao.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<nav class="navbar navbar-expand-lg " style="background-color:rgba(45,136,253,1); color:white;">
    <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="color:white; font-weight:bold;">Explora Tour</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">

                <a class="nav-link" asp-controller="Home" asp-action="Index" style="color:white; display:flex;">
                    <img style="width:22px;" src="~/img/casa (1).png" />
                    <span>&nbsp;Início</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Destinos" asp-action="Index" style="color:white;">
                    <img style="width:22px;" src="~/img/mapas-e-bandeiras.png" />
                    <span>&nbsp;Destinos</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Favoritos" asp-action="Index" style="color:white;">
                    <img style="width:22px;" src="~/img/favorito.png" />
                    <span>&nbsp;Favoritos</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Cadastro" asp-action="Cadastrar" style="color:white;">
                    <img style="width:22px;" src="~/img/pessoa.png" />
                    <span>&nbsp;Login</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

<div data-aos="fade-up" style="width: 100%; display: flex;  justify-content: center; margin-top:30px;">
    <div style="width: 80%;">
        @if (@ViewBag.cardAtualizar.CAImagem == null)
        {
        <img style="width:100%; height:60%;" src="~/img/imagem.png" class="card-img-top" alt="...">
        }
<h5 class="card-title">@ViewBag.cardAtualizar.CAID</h5>
<p class="card-text">@ViewBag.cardAtualizar.CADescricaoG</p>
<a href="/Destinos" class="btn btn-primary">Voltar</a>
    </div>
</div>

ExplorarTour/Views/Destinos/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site de Turismo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <style>
        .card{
            margin-bottom:10px;
        }
        .card:hover{
            transform:scale(1.07);
            transition:linear 100ms;
            animation:ease-in-out;
        }

        .favorito_false{
            transition: background-image 0.5s ease;
        }
        .favorito_false:hover{
            background-image: url('~/img/favorito (2).png');
        }
          
        
    </style>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg " style="background-color:rgba(45,136,253,1); color:white;">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="color:white; font-weight:bold;">Explora Tour</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">

                    <a class="nav-link" asp-controller="Home" asp-action="Index" style="color:white; display:flex;">
                        <img style="width:22px;" src="~/img/casa (1).png" />
                        <span>&nbsp;Início</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Destinos" asp-action="Index" style="color:white;">
                        <img style="width:22px;" src="~/img/mapas-e-bandeiras.png" />
                        <span>&nbsp;Destinos</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Favoritos" asp-action="Index" style="color:white;">
                        <img style="width:22px;" src="~/img/favorito.png" />
                        <span>&nbsp;Favoritos</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cadastro" asp-action="Cadastrar" style="color:white;">
                        <img style="width:22px;" src="~/img/pessoa.png" />
                        <span>&nbsp;Login</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div data-aos="fade-up" style="display:flex; flex-direction:column; justify-content: center; align-content: center; align-items: center;">
        <div style="width:80%;">
            <h1 style="margin-top:45px; font-weight:bold;">Destinos &nbsp;<a href="/Destinos/Criacao" class="btn btn-primary">+</a></h1>
            <span>@ViewBag.listaCardCount Itens</span>

           
        </div>
    </div>

  



    <div data-aos="fade-up" style="width: 100%; display: flex; align-content: center; align-items: center; justify-content: center; margin-top:10px;">
        <div style="width:80%;  display: grid;  grid-template-columns: repeat(3, 1fr); grid-column-gap: 10px; grid-row-gap: 1.2em;">

         
            @foreach (var item in @ViewBag.listaCard)
            {
                <div class="card" style="width: 18rem;">
                    <img src="~/img/imagem.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@item.CANome</h5>
                        <p class="card-text">@item.CADescricaoP</p>
                        <div style="display: flex; justify-content: space-between; ">
                            <a href="/Destinos/Descricao/@item.CAID" class="btn btn-primary">Viajar</a>
                                @if (item.favorito == 0)
                                {

                                <a id="favorito" href="/Destinos/Favoritar/@item.CAID"> <img class="favorito_false" src="~/img/favorito (1).png" /></a>
                                }
                                else
                                {

                                    <a href="/Destinos/Favoritar/@item.CAID"> <img src="~/img/favorito (2).png" /></a>
                                }

                          
                        </div>
                      
                  
 
                    </div>
                </div>
            }


           @* <h1> Teste</h1>

            <div>
                <input type="text" id="termoPesquisa" />
                <button id="btnPesquisar">Pesquisar</button>
            </div>
            <div id="resultadoPesquisa"></div>*@
        </div>


    </body>
    <script>
    AOS.init();

    $(document).ready(function () {
        $("#btnPesquisar").click(function () {
            var termoPesquisa = $("#termoPesquisa").val();
            $.ajax({
                url: '@Url.Action("Pesquisar", "Destinos")',
                data: { termoPesquisa: termoPesquisa },
                success: function (result) {
                    $("#resultadoPesquisa").html(result);
                }
            });
        });

        $("#favorito").click(function () {
            e.preventDefault(); // Isso evita que o link redirecione imediatamente

            // Extrair o valor do CAID do atributo "href"
            var href = $(this).attr("href");
            var caid = href.split('/').pop(); // Isso assume que o CAID está no final da URL

            // Agora, você pode usar a variável "caid" conforme necessário
            console.log(caid);
            $.ajax({
                url: '@Url.Action("Favoritar", "Destinos")',
                data: { id: id },
                success: function (result) {
                   alert("foi")
                }
            });
        });
    });
</script>


</html>

ExplorarTour/Views/Destinos/_ResultadoPesquisa.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Card>

@if (Model.Count > 0)
{
    @foreach (var item in Model)
    {
        <div class="card" style="width: 18rem;">
            <img src="~/img/imagem.png" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">@item.CANome</h5>
                <p class="card-text">@item.CADescricaoP</p>
                <div style="display: flex; justify-content: space-between; ">
                    <a href="/Destinos/Descricao/@item.CAID" class="btn btn-primary">Viajar</a>
                    @if (item.favorito == 0)
                    {

                        <a href="/Destinos/Favoritar/@item.CAID"> <img class="favorito_false" src="~/img/favorito (1).png" /></a>
                    }
                    else
                    {

                        <a href="/Destinos/Favoritar/@item.CAID"> <img src="~/img/favorito (2).png" /></a>
                    }


                </div>



            </div>
        </div>
    }
}
else
{
    <p>Nenhum resultado encontrado.</p>
}

ExplorarTour/Views/Favoritos/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site de Turismo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <style>

        html,body{
            margin:0;
            border:0;
            width:100%;
            height:100%;
        }
        .card {
            margin-bottom: 10px;
        }

            .card:hover {
                transform: scale(1.07);
                transition: linear 100ms;
                animation: ease-in-out;
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg " style="background-color:rgba(45,136,253,1); color:white;">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="color:white; font-weight:bold;">Explora Tour</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">

                    <a class="nav-link" asp-controller="Home" asp-action="Index" style="color:white; display:flex;">
                        <img style="width:22px;" src="~/img/casa (1).png" />
                        <span>&nbsp;Início</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Destinos" asp-action="Index" style="color:white;">
                        <img style="width:22px;" src="~/img/mapas-e-bandeiras.png" />
                        <span>&nbsp;Destinos</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Favoritos" asp-action="Index" style="color:white;">
                        <img style="width:22px;" src="~/img/favorito.png" />
                        <span>&nbsp;Favoritos</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Cadastro" asp-action="Cadastrar" style="color:white;">
                        <img style="width:22px;" src="~/img/pessoa.png" />
                        <span>&nbsp;Login</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <div data-aos="fade-up" style="display:flex; flex-direction:column; justify-content: center; align-content: center; align-items: center;">
        <div style="width:80%;">
            <h1 style="margin-top:45px; font-weight:bold;">Seus Pontos Turísticos Favoritos</h1>
            <span>@ViewBag.listaCardFavoritoCount Itens</span>
        </div>
    </div>

    <div data-aos="fade-up" style="width: 100%; display: flex; align-content: center; align-items: center; justify-content: center; margin-top:10px;">
        <div style="width:80%;  display: grid;  grid-template-columns: repeat(3, 1fr); grid-column-gap: 10px; grid-row-gap: 1.2em;">
            @if (@ViewBag.listaCardFavoritoCount != 0)
            {
                @foreach (var item in @ViewBag.listaCardFavorito)
                {
                    <div class="card" style="width: 18rem;">
                        <img src="~/img/imagem.png" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@item.CANome</h5>
                            <p class="card-text">@item.CADescricaoP</p>
        
                            <div style="display: flex; justify-content: space-between; ">
                                <a href="/Destinos/Descricao/@item.CAID" class="btn btn-primary">Viajar</a>
                              
                                

                                    <a href="/Favoritos/Favoritar/@item.CAID"> <img src="~/img/cancelar.png" /></a>
                                


                            </div>

                        </div>
                    </div>
                }
            }
            else
            {
                <div class="card" style="width: 18rem;">
                    <img src="~/img/imagem.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Escolha seu Destino Favorito</h5>
                        <a href="#" class="btn btn-primary">Ir</a>
                    </div>
                </div>
            }

        </div>
    </div>
   

</body>
<script>
    AOS.init();
</script>
</html>